import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'

import Form from '../components/Form'
import { useState, useEffect } from 'react'
import Error from '../components/Error'
import Weather from '../components/Weather'



interface Data {
  city: string,
  country: string;
}

const Home = () => {

  // HOOKS
  const [city, saveCity] = useState('');
  const [country, saveCountry] = useState('');
  const [error, saveError] = useState(false);
  const [result, saveResult] = useState({});

  useEffect(() => {
    //prevenir primera ejecucion
    if(city === '' || country === '') return;
    consultAPI()
  }, [city])


  const dataConsult = (data: Data) => {

    if (data.city === '' || data.country === '') {
      saveError(true);
      return;

    }

    saveCity(data.city);
    saveCountry(data.country)
    saveError(false);
  }

const consultAPI = async () => {

  const appId = '76144a3e64949b0e6238d8c6ef2f4215'
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city},${country}&appid=${appId}`

  const response = await fetch(url)
  const result = await response.json()

  saveResult(result)
}

  let component;
  let {cod} : any = result
 
  if (error) {

    component = <Error mensaje='Ambos campos son obligatorios' />
  }
  else if(cod === "404"){
    component = <Error mensaje='La ciudad no esta en el pais establecido' />
  } 
  else {
    component = <Weather result = {result} />
  }


  return (
    <div className="App">
     
     
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
      </Head>

        <Header HeaderTitle="Clima"/>
      

      <div className="contenedor-form">
        <div className="container">
          <div className="row">
            <div className="col s12 m6">
              <Form dataConsult={dataConsult}/>
            </div>
          </div>
        </div>
      </div>

      <div  className="col s12 m6">
        {component}
      </div>
    </div>

  )
}

export default Home

