import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import Form from '../components/Form'
import { useState } from 'react'
import Error from '../components/Error'


interface Data {
  city: string,
  country: string;
}

const Home: NextPage = () => {

  const [city, saveCity] = useState('');
  const [country, saveCountry] = useState('');
  const [error, saveError] = useState(false);

  const dataConsult = (data: Data) => {
    if (data.city === '' || data.country === '') {
      saveError(true);
      return;

    }

    saveCity(data.city);
    saveCountry(data.country)
    saveError(false);
  }


let component;
if(error) {

  component = <Error mensaje = 'Ambos campos son obligatorios'/>
} else{
component = null;
}


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header HeaderTitle="Clima"></Header>
      <Form dataConsult={dataConsult}></Form>

      <div>
        {component}
      </div>
    </div>
  )
}

export default Home
